/**
 * Symbol.js
 * Initial list of Stock & Crypto symbols (max 200+) that will be loaded by the Vue application.
 * Finnhub API Symbol Format:
 * - Stocks AS: CODE (e.g., NVDA)
 * - Stocks Non-US: EXCHANGE:CODE (e.g., LSE:VOD) - Note that Finnhub may require this format for non-US.
 * - Crypto: CODE/USDT (for front-end input, will be converted to BINANCE:CODEUSDT when fetching)
 */

export default [
  // US STOCK
  { code: 'TSM', name: ' Taiwan Semiconductor Manufacturing Co., Ltd. (ADR)' },  
  { code: 'AMZN', name: 'Amazon.com Inc.' },
  { code: 'TSLA', name: 'Tesla Inc.' },
  { code: 'JPM', name: 'JPMorgan Chase & Co.' },
  { code: 'JNJ', name: 'Johnson & Johnson' },
  { code: 'V', name: 'Visa Inc.' },
  { code: 'PG', name: 'Procter & Gamble Co.' },
  { code: 'UNH', name: 'UnitedHealth Group Inc.' },
  { code: 'HD', name: 'Home Depot Inc.' },
  { code: 'DIS', name: 'Walt Disney Co.' },
  { code: 'PYPL', name: 'PayPal Holdings Inc.' },
  { code: 'ADBE', name: 'Adobe Inc.' },
  { code: 'NFLX', name: 'Netflix Inc.' },
  { code: 'CRM', name: 'Salesforce Inc.' },
  { code: 'INTC', name: 'Intel Corporation' },
  { code: 'CSCO', name: 'Cisco Systems Inc.' },
  { code: 'PEP', name: 'PepsiCo Inc.' },
  { code: 'T', name: 'AT&T Inc.' },
  { code: 'ABT', name: 'Abbott Laboratories' },
  { code: 'LLY', name: 'Eli Lilly and Company' },
  { code: 'COST', name: 'Costco Wholesale Corporation' },
  { code: 'AVGO', name: 'Broadcom Inc.' },
  { code: 'TMO', name: 'Thermo Fisher Scientific Inc.' },
  { code: 'ABBV', name: 'AbbVie Inc.' },
  { code: 'WMT', name: 'Walmart Inc.' },
  { code: 'BAC', name: 'Bank of America Corporation' },
  { code: 'XOM', name: 'Exxon Mobil Corporation' },
  { code: 'MA', name: 'Mastercard Incorporated' },
  { code: 'CVX', name: 'Chevron Corporation' },
  { code: 'NKE', name: 'Nike Inc.' },
  { code: 'MRK', name: 'Merck & Co. Inc.' },
  { code: 'PFE', name: 'Pfizer Inc.' },
  { code: 'CMCSA', name: 'Comcast Corporation' },
  { code: 'KO', name: 'Coca-Cola Company' },
  { code: 'DHR', name: 'Danaher Corporation' },
  { code: 'ACN', name: 'Accenture plc' },
  { code: 'WFC', name: 'Wells Fargo & Company' },
  { code: 'MCD', name: "McDonald's Corporation" },
  { code: 'TXN', name: 'Texas Instruments Incorporated' },
  { code: 'VZ', name: 'Verizon Communications Inc.' },
  { code: 'NEE', name: 'NextEra Energy Inc.' },
  { code: 'RTX', name: 'RTX Corporation' },
  { code: 'UPS', name: 'United Parcel Service Inc.' },
  { code: 'PM', name: 'Philip Morris International Inc.' },
  { code: 'LIN', name: 'Linde plc' },
  { code: 'HON', name: 'Honeywell International Inc.' },
  { code: 'SBUX', name: 'Starbucks Corporation' },
  { code: 'AMD', name: 'Advanced Micro Devices Inc.' },
  { code: 'IBM', name: 'International Business Machines Corporation' },
  { code: 'ORCL', name: 'Oracle Corporation' },
  { code: 'QCOM', name: 'Qualcomm Incorporated' },
  { code: 'TGT', name: 'Target Corporation' },
  { code: 'LOW', name: "Lowe's Companies Inc." },
  { code: 'SPGI', name: 'S&P Global Inc.' },
  { code: 'UNP', name: 'Union Pacific Corporation' },
  { code: 'CAT', name: 'Caterpillar Inc.' },
  { code: 'DE', name: 'Deere & Company' },
  { code: 'GS', name: 'Goldman Sachs Group Inc.' },
  { code: 'AXP', name: 'American Express Company' },
  { code: 'PLTR', name: 'Palantir Technologies Inc.' },
  { code: 'NOW', name: 'ServiceNow Inc.' },
  { code: 'INTU', name: 'Intuit Inc.' },
  { code: 'AMAT', name: 'Applied Materials Inc.' },
  { code: 'ISRG', name: 'Intuitive Surgical Inc.' },
  { code: 'MU', name: 'Micron Technology Inc.' },
  { code: 'LRCX', name: 'Lam Research Corporation' },
  { code: 'ADI', name: 'Analog Devices Inc.' },
  { code: 'MDT', name: 'Medtronic plc' },
  { code: 'GILD', name: 'Gilead Sciences Inc.' },
  { code: 'BMY', name: 'Bristol-Myers Squibb Company' },
  { code: 'C', name: 'Citigroup Inc.' },
  { code: 'BLK', name: 'BlackRock Inc.' },
  { code: 'AMGN', name: 'Amgen Inc.' },
  { code: 'SCHW', name: 'Charles Schwab Corporation' },
  { code: 'MMM', name: '3M Company' },
  { code: 'GE', name: 'General Electric Company' },
  { code: 'F', name: 'Ford Motor Company' },
  { code: 'BA', name: 'Boeing Company' },
  { code: 'SO', name: 'Southern Company' },
  { code: 'DUK', name: 'Duke Energy Corporation' },
  { code: 'D', name: 'Dominion Energy Inc.' },
  { code: 'AEP', name: 'American Electric Power Company Inc.' },
  { code: 'EXC', name: 'Exelon Corporation' },
  { code: 'SRE', name: 'Sempra Energy' },
  { code: 'NEM', name: 'Newmont Corporation' },
  { code: 'GD', name: 'General Dynamics Corporation' },
  { code: 'LMT', name: 'Lockheed Martin Corporation' },
  { code: 'NOC', name: 'Northrop Grumman Corporation' },
  { code: 'SPG', name: 'Simon Property Group Inc.' },
  { code: 'PSA', name: 'Public Storage' },
  { code: 'EQIX', name: 'Equinix Inc.' },
  { code: 'WELL', name: 'Welltower Inc.' },
  { code: 'PLD', name: 'Prologis Inc.' },
  { code: 'CCI', name: 'Crown Castle Inc.' },
  { code: 'AMT', name: 'American Tower Corporation' },
  { code: 'SBAC', name: 'SBA Communications Corporation' },
  { code: 'AAPL', name: 'Apple Inc' },
  { code: 'MSFT', name: 'Microsoft Corp' },
  { code: 'GOOGL', name: 'Alphabet Inc Class A' },
  { code: 'META', name: 'Meta Platforms Inc' },
  { code: 'NVDA', name: 'NVIDIA Corp' },
  { code: 'ABNB', name: 'Airbnb Inc' },
  { code: 'UBER', name: 'Uber Technologies Inc' },
  { code: 'LYFT', name: 'Lyft Inc' },
  { code: 'SNOW', name: 'Snowflake Inc' },
  { code: 'SHOP', name: 'Shopify Inc' },
  { code: 'SOFI', name: 'SoFi Technologies Inc' },
  { code: 'ROKU', name: 'Roku Inc' },
  { code: 'SPOT', name: 'Spotify Technology SA' },
  { code: 'MRNA', name: 'Moderna Inc' },
  { code: 'GM', name: 'General Motors Co' },
  
  // INTERNATIONAL STOCKS
  { code: 'VOD', name: 'Vodafone Group Plc (UK)' },
  { code: 'BP', name: 'BP plc (UK)' },
  { code: 'SHELL', name: 'Shell plc (UK)' },
  { code: 'HSBA', name: 'HSBC Holdings plc (UK)' },
  { code: 'RIO', name: 'Rio Tinto Group (UK)' },
  { code: 'ULVR', name: 'Unilever PLC (UK)' },
  { code: 'SHEL', name: 'Shell plc (UK/NL)' },
  { code: 'BAYN', name: 'Bayer AG (Germany)' },
  { code: 'SAP', name: 'SAP SE (Germany)' },
  { code: 'SIE', name: 'Siemens AG (Germany)' },
  { code: 'VOW3', name: 'Volkswagen AG (Germany)' },
  { code: 'ALV', name: 'Allianz SE (Germany)' },
  { code: 'BAS', name: 'BASF SE (Germany)' },
  { code: 'ADS', name: 'adidas AG (Germany)' },
  { code: 'BMW', name: 'Bayerische Motoren Werke AG (Germany)' },
  { code: 'RMS', name: 'Hermès International SCA (France)' },
  { code: 'CDI', name: 'Compagnie de Saint-Gobain S.A. (France)' },
  { code: 'AIR', name: 'Airbus SE (France/NL)' },
  { code: 'LVMUY', name: 'LVMH Moët Hennessy Louis Vuitton SE (ADR)' },
  { code: 'ORAN', name: 'Orange S.A. (France)' },
  { code: 'SAN', name: 'Sanofi (France)' },
  { code: 'REP', name: 'Repsol S.A. (Spain)' },
  { code: 'IBE', name: 'Iberdrola, S.A. (Spain)' },
  { code: 'BBVA', name: 'Banco Bilbao Vizcaya Argentaria, S.A. (Spain)' },
  { code: 'ENI', name: 'Eni S.p.A. (Italy)' },
  { code: 'ISP', name: 'Intesa Sanpaolo S.p.A. (Italy)' },
  { code: 'STM', name: 'STMicroelectronics N.V. (Italy/France)' },
  { code: 'NESN', name: 'Nestlé S.A. (Switzerland)' },
  { code: 'ROG', name: 'Roche Holding AG (Switzerland)' },
  { code: 'NOVN', name: 'Novartis AG (Switzerland)' },
  { code: 'UBSG', name: 'UBS Group AG (Switzerland)' },
  { code: 'ZURN', name: 'Zurich Insurance Group AG (Switzerland)' },
  { code: 'ELISA', name: 'Elisa Oyj (Finland)' },
  { code: 'NDSNA', name: 'Nordea Bank Abp (Finland/Sweden)' },
  { code: 'ERICB', name: 'Ericsson LM Telephone Co. (Sweden)' },
  { code: 'VOLVB', name: 'Volvo AB (Sweden)' },
  { code: 'HMB', name: 'H & M Hennes & Mauritz AB (Sweden)' },
  { code: 'SAPL', name: 'Sasol Limited (South Africa)' },
  { code: 'BTI', name: 'British American Tobacco p.l.c. (UK/ADR)' },
  { code: 'RY', name: 'Royal Bank of Canada (Canada)' },
  { code: 'TD', name: 'Toronto-Dominion Bank (Canada)' },
  { code: 'SHOP', name: 'Shopify Inc. (Canada)' },
  { code: 'ENB', name: 'Enbridge Inc. (Canada)' },
  { code: 'BNS', name: 'Bank of Nova Scotia (Canada)' },
  { code: 'BHP', name: 'BHP Group Ltd (Australia/UK)' },
  { code: 'CBA', name: 'Commonwealth Bank of Australia (Australia)' },
  { code: 'NAB', name: 'National Australia Bank Limited (Australia)' },
  { code: 'WBC', name: 'Westpac Banking Corporation (Australia)' },
  { code: 'CSL', name: 'CSL Limited (Australia)' },
  { code: 'MIN', name: 'Mineral Resources Limited (Australia)' },
  { code: 'TLS', name: 'Telstra Corporation Limited (Australia)' },
  { code: 'SRE', name: 'Sempra Energy (US - Sudah ada, dipertahankan)' }, 
  { code: 'SBUX', name: 'Starbucks Corporation (US - Sudah ada, dipertahankan)' }, 
  { code: '005930', name: 'Samsung Electronics Co., Ltd. (South Korea)' },
  { code: '000660', name: 'SK Hynix Inc. (South Korea)' },
  { code: '7203', name: 'Toyota Motor Corporation (Japan)' },
  { code: '9984', name: 'SoftBank Group Corp. (Japan)' },
  { code: '8031', name: 'Mitsui & Co., Ltd. (Japan)' },
  { code: '4502', name: 'Takeda Pharmaceutical Co., Ltd. (Japan)' },
  { code: '8306', name: 'Mitsubishi UFJ Financial Group, Inc. (Japan)' },
  { code: '3938', name: 'LINE Corporation (Japan, Delisted - Contoh stok non-AS)' },
  { code: '0700', name: 'Tencent Holdings Ltd (Hong Kong)' },
  { code: '0939', name: 'China Construction Bank Corp (Hong Kong)' },
  { code: '0941', name: 'China Mobile Ltd (Hong Kong)' },
  { code: '9988', name: 'Alibaba Group Holding Ltd (Hong Kong)' },
  { code: '0388', name: 'HKEX - Hong Kong Exchanges and Clearing Ltd (Hong Kong)' },
  { code: '2330', name: 'Taiwan Semiconductor Manufacturing Co. (Taiwan)' }, // TSM adalah ADR, ini adalah saham lokal
  { code: '2454', name: 'MediaTek Inc. (Taiwan)' },
  { code: '2317', name: 'Hon Hai Precision Industry Co., Ltd. (Foxconn) (Taiwan)' },
  { code: 'RELIANCE', name: 'Reliance Industries Ltd (India)' },
  { code: 'TCS', name: 'Tata Consultancy Services Ltd (India)' },
  { code: 'INFY', name: 'Infosys Ltd (India)' },
  { code: 'HDB', name: 'HDFC Bank Limited (India)' },
  { code: 'SAUDI ARAMCO', name: 'Saudi Arabian Oil Co. (Saudi Arabia)' },
  { code: 'MC', name: 'LVMH Moet Hennessy Louis Vuitton SE (France)' },
  { code: 'SU', name: 'Schneider Electric SE (France)' },
  { code: 'GLE', name: 'Societe Generale S.A. (France)' },
  { code: 'ADIDAS', name: 'adidas AG (Germany - Dihapus, gunakan ADS)' },
  { code: 'FRE', name: 'Fresenius SE & Co. KGaA (Germany)' },
  { code: 'ENEL', name: 'Enel S.p.A. (Italy)' },
  { code: 'UCG', name: 'UniCredit S.p.A. (Italy)' },
  { code: 'SAN', name: 'Santander (Spain - Sudah ada, dipertahankan)' },
  { code: 'TEF', name: 'Telefónica, S.A. (Spain)' },
  { code: 'COLOPL', name: 'Colopl, Inc. (Japan - Sektor game)' },
  { code: 'FANCL', name: 'Fancl Corporation (Japan - Kosmetik)' },
  { code: 'SEB', name: 'SEB SA (France - Peralatan rumah tangga)' },
  { code: 'KNEB', name: 'Koninklijke Nedbank N.V. (Netherlands)' },
  { code: 'ASML', name: 'ASML Holding N.V. (Netherlands)' },
  { code: 'PHIA', name: 'Koninklijke Philips N.V. (Netherlands)' },
  { code: 'CRH', name: 'CRH plc (Ireland - Bahan bangunan)' },
  { code: 'BOLS', name: 'Lucas Bols N.V. (Netherlands - Minuman)' },
  { code: 'ALFEN', name: 'Alfen N.V. (Netherlands - Energi terbarukan)' },
  { code: 'WIZZ', name: 'Wizz Air Holdings Plc (UK - Maskapai)' },
  { code: 'MUV2', name: 'Muenchener Rueckversicherungs-Gesellschaft AG (Germany)' },
  { code: 'DBK', name: 'Deutsche Bank AG (Germany)' },
  { code: 'RNO', name: 'Renault SA (France)' },
  { code: 'KER', name: 'Kering SA (France)' },
  { code: 'ISP', name: 'Intesa Sanpaolo SpA (Italy - Sudah ada, dipertahankan)' },
  { code: 'EXOR', name: 'Exor N.V. (Netherlands - Perusahaan investasi)' },
  { code: 'ATCO', name: 'Atlas Copco AB (Sweden)' },
  { code: 'NOVOB', name: 'Novo Nordisk A/S (Denmark - Farmasi)' },
  { code: 'MAERSK B', name: 'A.P. Møller-Mærsk A/S (Denmark - Pengiriman)' },
  { code: 'BCE', name: 'BCE Inc. (Canada)' },
  { code: 'TRP', name: 'TC Energy Corporation (Canada)' },
  { code: 'ZIM', name: 'ZIM Integrated Shipping Services Ltd. (Israel)' },

  // CRYPTO
  { code: 'BTC/USDT', name: 'Bitcoin / Tether' },
  { code: 'ETH/USDT', name: 'Ethereum / Tether' },
  { code: 'BNB/USDT', name: 'Binance Coin / Tether' },
  { code: 'SOL/USDT', name: 'Solana / Tether' },
  { code: 'ADA/USDT', name: 'Cardano / Tether' },
  { code: 'XRP/USDT', name: 'Ripple / Tether' },  
  { code: 'DOGE/USDT', name: 'Dogecoin / Tether' },
  { code: 'AVAX/USDT', name: 'Avalanche / Tether' },
  { code: 'DOT/USDT', name: 'Polkadot / Tether' },
  { code: 'MATIC/USDT', name: 'Polygon / Tether' },
  { code: 'LTC/USDT', name: 'Litecoin / Tether' },
  { code: 'TRX/USDT', name: 'TRON / Tether' },
  { code: 'LINK/USDT', name: 'Chainlink / Tether' },
  { code: 'UNI/USDT', name: 'Uniswap / Tether' },
  { code: 'ATOM/USDT', name: 'Cosmos / Tether' },
  { code: 'NEAR/USDT', name: 'NEAR Protocol / Tether' },
  { code: 'AAVE/USDT', name: 'Aave / Tether' },
  { code: 'OP/USDT', name: 'Optimism / Tether' },
  { code: 'ARB/USDT', name: 'Arbitrum / Tether' },
  { code: 'SUI/USDT', name: 'Sui / Tether' },
  { code: 'TIA/USDT', name: 'Celestia / Tether' },
  { code: 'PEPE/USDT', name: 'Pepe / Tether' },
  { code: 'INJ/USDT', name: 'Injective / Tether' },
  { code: 'RUNE/USDT', 'name': 'THORChain / Tether' },
  { code: 'FTM/USDT', name: 'Fantom / Tether' },
  { code: 'FIL/USDT', name: 'Filecoin / Tether' },
  { code: 'ETC/USDT', name: 'Ethereum Classic / Tether' },
  { code: 'EGLD/USDT', name: 'MultiversX / Tether' },
  { code: 'RNDR/USDT', name: 'Render / Tether' },
  { code: 'BTC/USDC', name: 'Bitcoin / USD Coin' },
  { code: 'ETH/BTC', name: 'Ethereum / Bitcoin' }
];
